name: seg_baseline
task_name: segmentation
base: configs/segmentation/_base.yaml

control:
  exceptions: []

splits:
  - name: custom_unet
    override:
      model: {name: custom_unet_seg, params: {num_classes: 3}}
  - name: deeplabv3_resnet50
    override:
      model:
        name: deeplabv3_resnet50_seg
        params: {num_classes: 3, backbone_name: resnet50, weights_path: /mnt/d/backbones/deeplabv3_resnet50_coco-cd0a2569.pth}
  - name: fcn_resnet50
    override:
      model:
        name: fcn_resnet50_seg
        params: {num_classes: 3, backbone_name: resnet50, weights_path: /mnt/d/backbones/fcn_resnet50_coco-1167a1af.pth}
