model:
  name: stfpm_anomaly
  params:
    backbone: resnet18
    weights_path: ${paths.backbone_root}/resnet18-f37072fd.pth

adapter:
  name: stfpm
  params:
    smooth_sigma: 4.0

optim:
  optimizer:
    name: sgd
    params:
      lr: 0.4
      momentum: 0.9
  scheduler:
    name: cosine
    params:
      t_max: 100
      eta_min: 0.0001

selectors:
  backbone:
    resnet18:
      model.params.backbone: resnet18
      model.params.weights_path: "${paths.backbone_root}/resnet18-f37072fd.pth"
    resnet50:
      model.params.backbone: resnet50
      model.params.weights_path: "${paths.backbone_root}/resnet50-0676ba61.pth"
    wide_resnet50_2:
      model.params.backbone: wide_resnet50_2
      model.params.weights_path: "${paths.backbone_root}/wide_resnet50_2-95faca4d.pth"
